### ISSUE TITLE
Samsung connection error

### ISSUE THREAD

**Issue by Gernair** [inUtil-info/whin2-contrib#2]
Hello, I installed the new whin in node red and wanted to use it again on my cell phone and on that of my wife.
But there are again the same problems as with the previous version.
There was no problem with my cell phone, with my wife it doesn't work again.
I send the message "whin-signup" here and wait for the reply but nothing comes.
Could you please help me

**Comment by lu4t** [comment]
You shouldn't be having this problem on the new release as the payload is sent in raw format.
Can you pls double check if you're sending the msg to the right number? (bear in mind it's a different number than the one used on the previous release).
Let us know.

**Comment by Gernair** [comment]
Hello, my wife's number has not changed.
It's still +49 1XXXX4207
She created an account on rapiapi and then sent the message but there was no reply.

I now have problems with my account in Node Red
I keep getting the message now
"[WHIN error] Unexpected server response: 401"
and
"[WHIN] Connection died"
I have to erase everything and restart Node Red then the error goes away.
I have already updated the node to the latest version.
But the error still remains

**Comment by Gernair** [comment]
My wife sent the message to +34 605 79 77 64.
Just like me

**Comment by lu4t** [comment]
Hi, this version is still under development. Update and give it a try.
I edited a previous post you did, to remove the phone number. Please do not include PII which is not relevant for anyone.
