### ISSUE TITLE
Installation of 0.0.5 fails

### ISSUE THREAD

**Issue by FireWizard52** [inUtil-info/whin2-contrib#3]
Hi,

I tried to upgrade from version 0.0.3 (which worked fine) to version 0.0.5

Both from "Palette" and from the "Command line" the installation fails.

At first instance it looks okay, but after configuration and deploying the flow stops, due to missing nodes.
In my case the send node and config node.

If you remove the Whin package, it shows that it has removed 2 copies from the installed (3) nodes, So totally 6 nodes were removed.

Regards

**Comment by lu4t** [comment]
@FireWizard52 thanks for the heads up.... our fault. Sorry for the inconvenience, we did  too many changes in the last few days and we messed up with this.

0.0.6 is published correcting the error. Please confirm if all is working for you now (it is for me on my tests).

**Comment by FireWizard52** [comment]
@lu4t
I installed the new version 0.0.6 (using the palette) and can confirm that it functions as expected. No issues.

Thanks for your quick response and providing a new version.

I think we can close this issue  for now.

Regards
