### ISSUE TITLE
Is it possible to send local image(s)?

### ISSUE THREAD

**Issue by Seba200086** [inUtil-info/whin2-contrib#4]
Hi,
I would like to ask if is it possible to send image from local disk? (I am using Whin with Node Red on Home Assistant)
All examples point to images on the web (https://...)
I would like to include a picture saved on the local disk (e.g. /config or /media)

**Comment by lu4t** [comment]
Hi,
when you send an image (or any other MIME type file) on whatsapp, the whatsapp client encrypts the content. As whin is a shared whatsapp gateway (client), the only way you would have to send a file would be as explained on the examples.
If you don't want to host the image on any free site (accessible through https), technically you could expose your /config or /media local folders and send the file, and then send the whatsapp message using whin with an url to access your files.
